package central_banking_system;

public enum ApprovalType {
    MAJOR_MONETARY_POLICY_CHANGE,
    POLICY_INTEREST_RATE_CHANGE,
    MONEY_SUPPLY_ADJUSTMENT,
    COMMERCIAL_BANK_REGISTRATION_APPROVAL,
    COMMERCIAL_BANK_LICENCE_APPROVAL,
    COMMERCIAL_BANK_LICENCE_REVOCATION,
    COMMERCIAL_BANK_SUSPENSION,
    COMMERCIAL_BANK_CLOSURE,
    NATIONAL_FINANCIAL_REPORT_APPROVAL,
    FOREIGN_EXCHANGE_RESERVE_MANAGEMENT,
    FRAUD_INVESTIGATION_DECISION,
    FINANCIAL_STABILITY_DECISION,
    NATIONAL_BANKING_REGULATION
}
